### ISSUE TITLE
Support for `caption`, `thead`, `tfoot` in tables

### ISSUE THREAD

**Issue by SiddharthShyniben** [kognise/water.css#275]
Suggested `caption` style:

```css
caption {
    padding: 10px;
    caption-side: bottom;
}
```

Suggested `thead`/`tfoot` style:

```css
thead,
tfoot {
    background-color: #333;
    color: #fff;
}
```
