### ISSUE TITLE
Format Definition List vertical

### ISSUE THREAD

**Issue by jimmywarting** [kognise/water.css#299]
Following up on this article on how to format a [Definition List](https://www.the-art-of-web.com/css/format-dl/) and some other stackoverflow suggestions... I found this to be pretty nice: https://jsbin.com/kuyawicuno/2/edit?html,css,output

Thinking maybe that you should incorporate it to the default style

**Comment by deepbeatz** [comment]
please assign me this issue. I want to start working on it immediately.

**Comment by adiitiii** [comment]
Can you explain in a more detail manner as to what exactly needs to be done here ? I'm still confused, I'd like to contribute

**Comment by jimmywarting** [comment]
Simply adding: 
```css
dl {
	display: grid;
	align-items: baseline;
}
dt {
	grid-column: 1;
	text-align: right;
}
dd {
	grid-column: 2;
	margin-inline-start: 10px;
}
dd * {
	width: 100%;
	box-sizing: border-box;
}
```
