### ISSUE TITLE
make use of `color-scheme: dark;`

### ISSUE THREAD

**Issue by jimmywarting** [kognise/water.css#300]
Many native controllers like checkboxes and eg the small date icon on `input[type=datetime-local]` have quite a bad contrast when using the prefer dark mode.

that is b/c it still renders dose native controllers as light theme. 
i think this should be added:
```css
@media (prefers-color-scheme: dark) {
  * { color-scheme: dark; }
}
```
by using this ☝️ then i don't think you really have to go for all the trouble of styling native buttons and input that much...

the native calender will get a dark mode when using this 👍
