### ISSUE TITLE
<address> and links inside

### ISSUE THREAD

**Issue by kylejrp** [kognise/water.css#44]
We can style the `<address>` element, or more specifically, the links inside!

MDN has good documentation:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/address

They've put icons before each type of link by using the following selectors:
```
a[href^="mailto"]::before {
    content: "📧 ";
}

a[href^="tel"]::before {
    content: "📞 ";
}
```

We could probably do something more interesting here, but I'm not a great designer and nothing's coming to mind. Any ideas?

**Comment by kognise** [comment]
I actually quite like this! My only change would be to un-italicize them - is this bad practice?

```css
address {
  font-style: normal;
}

a[href^='mailto']::before {
    content: "📧 ";
}

a[href^='tel']::before {
    content: "📞 ";
}
```
