### ISSUE TITLE
::selection

### ISSUE THREAD

**Issue by diomed** [kognise/water.css#52]
By darkening the background color by 40% we can get a nice background color for selections.

I propose adding something like this:

```scss
::selection {
  background-color: darken($background-color, 40%);
}
```
